markdown: rdiscount
pygments: true

# Template Settings
title: 'Apps and the City Network'
location: 'Deutschland'
date: 'Established 2012'

# Navigation
navigation:
- text: 'Berlin'
  url: 'http://berlin.appsandthecity.net'
- text: 'Köln'
  url: 'http://berlin.appsandthecity.net'
